# Generated by Django 4.2 on 2023-09-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0005_rename_memberstudiorelationships_memberstudiorelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioinfo',
            name='url',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
