# Generated by Django 4.2 on 2023-09-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0006_studioinfo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studioinfo',
            old_name='url',
            new_name='url_extension',
        ),
    ]
