# Generated by Django 4.2 on 2023-10-05 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0007_rename_url_studioinfo_url_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='KilnManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiln_name', models.CharField(max_length=100)),
                ('kiln_make', models.CharField(max_length=100)),
                ('kiln_model', models.CharField(max_length=100)),
                ('kiln_size', models.CharField(max_length=100)),
                ('kiln_max_temp', models.CharField(max_length=100)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_suite.studioinfo')),
            ],
        ),
    ]
