# Generated by Django 4.2 on 2023-10-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0008_kilnmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kilnmanagement',
            name='kiln_max_temp',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kilnmanagement',
            name='kiln_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
