# Generated by Django 4.2 on 2023-10-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0011_recurrenceday_bookingmanagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmanagement',
            name='recurrence_days',
        ),
        migrations.DeleteModel(
            name='RecurrenceDay',
        ),
    ]
