# Generated by Django 4.2 on 2023-10-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0012_remove_bookingmanagement_recurrence_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmanagement',
            name='max_bookings',
        ),
        migrations.AlterField(
            model_name='bookingmanagement',
            name='is_recurring',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Temporarily'), (2, 'Forever')], default=0),
        ),
    ]
