# Generated by Django 4.2 on 2023-10-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0013_remove_bookingmanagement_max_bookings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookingmanagement',
            name='recurring_weekdays',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='studio_suite.weekday'),
        ),
    ]
