# Generated by Django 4.2 on 2023-10-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0014_weekday_bookingmanagement_recurring_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmanagement',
            name='recurring_weekdays',
            field=models.ManyToManyField(blank=True, to='studio_suite.weekday'),
        ),
    ]
