# Generated by Django 4.2 on 2023-10-11 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0015_alter_bookingmanagement_recurring_weekdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeslotManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recurring', models.IntegerField(choices=[(0, 'Never'), (1, 'Temporarily'), (2, 'Forever')], default=0)),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('load_after_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('kiln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_suite.kilnmanagement')),
                ('recurring_weekdays', models.ManyToManyField(blank=True, to='studio_suite.weekday')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_suite.studioinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='BookingManagement',
        ),
    ]
