# Generated by Django 4.2 on 2023-10-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0016_timeslotmanagement_delete_bookingmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotmanagement',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, unique=True),
        ),
    ]
