# Generated by Django 4.2 on 2023-10-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0017_alter_timeslotmanagement_recurrence_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotmanagement',
            name='notes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
