# Generated by Django 4.2 on 2023-10-25 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0018_alter_timeslotmanagement_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeslotBlackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blackout_start_datetime', models.DateTimeField()),
                ('blackout_end_datetime', models.DateTimeField()),
                ('blackout_reason', models.TextField(blank=True, max_length=100, null=True)),
                ('related_timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_suite.timeslotmanagement')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_suite.studioinfo')),
            ],
        ),
    ]
