# Generated by Django 4.2 on 2023-10-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0019_timeslotblackout'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstudiorelationship',
            name='member_role',
            field=models.SmallIntegerField(choices=[(0, 'No Access Member'), (1, 'Regular Member'), (2, 'Premium Member'), (3, 'Technician'), (4, 'Studio Manager'), (5, 'Studio Owner')], default=1),
            preserve_default=False,
        ),
    ]
