# Generated by Django 4.2 on 2023-10-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0020_memberstudiorelationship_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioinfo',
            name='new_member_role',
            field=models.SmallIntegerField(choices=[(0, 'No Acccess Member'), (1, 'Regular Member')], default=0),
            preserve_default=False,
        ),
    ]
