# Generated by Django 4.2 on 2023-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0021_studioinfo_new_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberstudiorelationship',
            name='member_role',
            field=models.SmallIntegerField(choices=[('NA', 'No Access Member'), ('RM', 'Regular Member'), ('TECH', 'Technician'), ('MANAGER', 'Studio Manager'), ('OWNER', 'Studio Owner')]),
        ),
        migrations.AlterField(
            model_name='studioinfo',
            name='new_member_role',
            field=models.SmallIntegerField(choices=[('NA', 'No Acccess Member'), ('RM', 'Regular Member')]),
        ),
    ]
