# Generated by Django 4.2 on 2023-10-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0022_alter_memberstudiorelationship_member_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberstudiorelationship',
            name='member_role',
            field=models.CharField(choices=[('NA', 'No Access Member'), ('RM', 'Regular Member'), ('TECH', 'Technician'), ('MANAGER', 'Studio Manager'), ('OWNER', 'Studio Owner')], max_length=7),
        ),
    ]
