# Generated by Django 4.2 on 2023-11-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0024_timeslotmanagement_min_role_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotmanagement',
            name='min_role_required',
            field=models.CharField(choices=[('RM', 'Regular Member'), ('TECH', 'Technician'), ('MANAGER', 'Studio Manager')], max_length=7),
        ),
    ]
