# Generated by Django 4.2 on 2023-11-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0026_kilnrange_kilnmanagement_kiln_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kilnmanagement',
            name='kiln_name',
            field=models.CharField(max_length=100),
        ),
    ]
