# Generated by Django 4.2 on 2024-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_suite', '0027_alter_kilnmanagement_kiln_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioinfo',
            name='business_main_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studioinfo',
            name='currency',
            field=models.CharField(choices=[('C1', 'CAD'), ('C2', 'USD'), ('C3', 'EUR'), ('C4', 'JPY'), ('C5', 'GBP'), ('C6', 'CHF'), ('C7', 'CNY'), ('C8', 'AUD'), ('C9', 'INR'), ('C10', 'BRL')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='studioinfo',
            name='timezone',
            field=models.CharField(choices=[('Z1', 'GMT'), ('Z2', 'MST'), ('Z3', 'EST'), ('Z4', 'CST'), ('Z5', 'PST'), ('Z6', 'AEST'), ('Z7', 'ACST'), ('Z8', 'AWST'), ('Z9', 'CET'), ('Z10', 'EET')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='studioinfo',
            name='website_link',
            field=models.URLField(default=''),
        ),
    ]
